### ISSUE TITLE
Geopandas install issue version 0.6.3 vs 0.7

### ISSUE THREAD

**Issue by lwasser** [conda-forge/geopandas-feedstock#77]
Issue:
Hi there @ocefpaf !! 👋 👋 👋 
We are running into an unusual issue with our [docker container](https://github.com/earthlab/r-python-eds-lessons-env/pull/28). Essentially we are trying to update geopandas in it but it wants to install version 0.6.3 rather than .7 which has some new functionality that we want to use.

Is there a dependency resolution issue with geopandas right now OR is there something wrong with our dockerfile? We can't seem to figure out why it won't install the newest version. 

Thank you for any insight or suggestions! I am willing to try any different approaches that you suggest to getting this to work!

<br/>
Environment (<code>conda list</code>):

<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jorisvandenbossche** [comment]
What version of pyproj is it installing? That's the main thing that changes in geopandas 0.7, as we now require pyproj > 2.2, which requires PROJ > 6. There might be some other dependencies that still require an older proj/pyproj

**Comment by lwasser** [comment]
Ahhhhh @jorisvandenbossche it's installing `pyproj  1.9.6` NOT `> 2.2` so this makes sense. 
How would you go about trouble shooting this to try to get a stable container build with the latest geopandas? i'm open to suggestions. many thanks.

**Comment by ocefpaf** [comment]
> How would you go about trouble shooting this to try to get a stable container build with the latest geopandas? i'm open to suggestions. many thanks.

I usually create and env file with those dependencies and "force" `pyproj >=2` to check what is the problem.

I'm debugging your env now and I'll report back later but if I had to guess it is b/c you are using an old version of `R`.

PS: I'll report the results here but I'm closing this b/c the problem is not with geopandas and not even with conda-forge. Just a selection of packages that cannot be installed together.

**Comment by lwasser** [comment]
ahhhh ok no worries. i'll close this but will continue to watch. i wasn't sure where to start with this issue so I really appreciate this feedback. I hadn't considered that R could throw off an entire build. And now I know how to attempt to debug in the future. THANK YOU both again.

**Comment by ocefpaf** [comment]
If I force latest pyproj >=2 these packages cannot be installed in the env: r-raster, r-rastervis, r-rgeos, r-reshape, r-rsaga, r-sf

However, because an env like:

```
conda create --name TEST "pyproj=>2" r-raster r-rastervis r-rgeos r-reshape r-rsaga r-sf
```

is a possible solution, we probably have one or more of the other dependencies pinned to an older of one or more of the packages above. Maybe a re-build will solve this, maybe we'll need to wait for a new release of some package. I'll keep looking tomorrow.

**Comment by ocefpaf** [comment]
Ignore all that. The culprit is `basemap` I got it working with an env file like:

```yaml
name: TEST
channels:
  - conda-forge
dependencies:
  - python=3.7
  - r-base=3.6
  - autopep8
#   - basemap
  - cartopy
  - cenpy
  - climata
  - contextily
  - earthpy
  - elevation
  - folium
  - geocoder
  - geojson
  - geopandas
  - geopy
  - hydrofunctions
  - mapboxgl
  - mapclassify
  - nano
  - nbclean
  - nltk
  - papermill
  - pyproj >=2
  - pyqt
  - pysal
  - r-bookdown
  - r-codetools
  - r-cowplot
  - r-cyphr
  - r-curl
  - r-devtools
  - r-dplyr
  - r-dygraphs
  - r-ff
  - r-ggmap
  - r-ggplot2
  - r-ggsn
  - r-gridextra
  - r-kableextra  
  - r-knitr
  - r-lemon
  - r-magick
  - r-mapdata 
  - r-maps
  - r-maptools
  - r-microbenchmark 
  - r-plotly
  - r-r.utils
  - r-raster
  - r-rastervis
  - r-rgdal
  - r-rgeos
  - r-rjsonio
  - r-rmarkdown
  - r-reshape
  - r-rsaga
  - r-rtweet
  - r-sf
  - r-stringr
  - r-widyr
  - r-tm
  - r-igraph
  - r-leaflet
  - r-lubridate
  - r-rcurl
  - r-ggraph
  - r-ggthemes
  - r-gganimate
  - r-webshot
  - r-zoo
  - rasterio
  - rasterstats
  - richdem
  - scikit-image
  - scikit-learn
  - shapely
  - textblob
  - tweepy
```

I'll see what I can do on the conda-forge side but I'm not hopeful. Basemap is deprecated and quite hard for us to rebuild it with newer software.
